baseurl = "https://Pismery.github.io"
title = "Pismery Blog"

theme = "hugo-theme-cleanwhite"
#theme = "timer-hugo"
#theme = "hugo-pacman-theme"
#theme = "hugo-theme-air"
#theme = "hugo-nuo"
#theme = "jeffprod"
#theme = "sam"
#theme = "coder-portfolio"

languageCode = "utf-8"
# Enable comments by entering your Disqus shortname
disqusShortname = ""
googleAnalytics = ""
preserveTaxonomyNames = true
paginate = 10 #frontpage pagination
hasCJKLanguage = true

[outputs]
home = ["HTML", "RSS", "Algolia"]

[params]
  header_image = "img/home-bg2.jpg"
  SEOTitle = "刘嘉禾的博客 | Pismery Liu Blog"
  description = "程序员"
  keyword = "Pismery Johonr 博客"
  slogan = "路在脚下，心向远方"

  image_404 = "img/404-bg.jpg"
  title_404 = "你来到了没有知识的荒原 :("

  # leancloud storage for page view counter
  page_view_conter = false
  leancloud_app_id = ""
  leancloud_app_key = ""

  # algolia site search
  algolia_search = false 
  algolia_appId = ""
  algolia_indexName = ""
  algolia_apiKey = ""

  # Sidebar settings
  sidebar_about_description = "Java Developer"
  sidebar_avatar = "img/head.jpg"      # use absolute URL, seeing it's used in both `/` and `/about/`

  featured_tags = true 
  featured_condition_size = 0

  # Baidu Analytics
  ba_track_id = ""
  
  # We need a proxy to access Disqus api in China
  disqus_proxy = ""
  disqus_site = ""

  #wechat pay & alipay 
  reward = false
  reward_guide = "如果这篇文章对你有用，请随意打赏" 

  [params.social]
  #rss            = true 
  email          = "pismery@163.com"
  #facebook      = "full profile url in facebook"
  #googleplus    = "full profile url in googleplus"
  #twitter       = "full profile url in twitter"
  #linkedin       = "full profile url in linkedin"
  #stackoverflow  = "full profile url in stackoverflow"
  #instagram     = "full profile url in instagram"
  github         = "https://github.com/Pismery"
  gitee         = "https://gitee.com/pismery"
  #wechat         = "wechat-code.jpg" 
  #pinterest     = "full profile url in pinterest"
  
  [[params.friend_link]]
  #title = "Linda的博客"
  #href =  "https://zhaozhihan.com"

  #[[params.bookmark_link]]
  #title =  "Martin Fowler"
  #href =  "https://martinfowler.com"
  #[[params.bookmark_link]]
  #title = "ServiceMesh中文网"
  #href =  "http://www.servicemesh.cn"
  #[[params.bookmark_link]]
  #title = "Awesome Service Mesh"
  #href = "https://servicemesh.gitbooks.io/awesome-servicemesh"
  #[[params.bookmark_link]]
  #title =  "Image Compression"
  #href = "https://tinypng.com"
  
[outputFormats.Algolia]
baseName = "algolia"
isPlainText = true
mediaType = "application/json"
notAlternative = true

[params.algolia]
vars = ["title", "summary", "date", "publishdate", "expirydate", "permalink"]
params = ["categories", "tags"] 
